#!/usr/bin/env escript

%% TODO: finish this off

main([M, F, A]) ->
	case code:which(M) of
		non_existing ->
			io:format("", []);
		BinPath ->
			process(M,F,A)
	end.

process(M,F,A) ->
	case erlang:function_exported(M, F, A) of
		false ->
			reload(M),
			process(M, F, A);
		true ->
			AC = apply(M, '$abstract_code$', []),
			ok
	end.
	
